//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diabetes {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources_ar {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources_ar() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Diabetes.AppResources.ar", typeof(AppResources_ar).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string username {
            get {
                return ResourceManager.GetString("username", resourceCulture);
            }
        }
        
        internal static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        internal static string loginpage {
            get {
                return ResourceManager.GetString("loginpage", resourceCulture);
            }
        }
        
        internal static string loginbutton {
            get {
                return ResourceManager.GetString("loginbutton", resourceCulture);
            }
        }
        
        internal static string signupbutton {
            get {
                return ResourceManager.GetString("signupbutton", resourceCulture);
            }
        }
        
        internal static string home_nav {
            get {
                return ResourceManager.GetString("home_nav", resourceCulture);
            }
        }
        
        internal static string therapy_nav {
            get {
                return ResourceManager.GetString("therapy_nav", resourceCulture);
            }
        }
        
        internal static string trackme_nav {
            get {
                return ResourceManager.GetString("trackme_nav", resourceCulture);
            }
        }
        
        internal static string settings_nav {
            get {
                return ResourceManager.GetString("settings_nav", resourceCulture);
            }
        }
        
        internal static string therapy_home {
            get {
                return ResourceManager.GetString("therapy_home", resourceCulture);
            }
        }
        
        internal static string insulin_tracking {
            get {
                return ResourceManager.GetString("insulin_tracking", resourceCulture);
            }
        }
        
        internal static string therapy_title {
            get {
                return ResourceManager.GetString("therapy_title", resourceCulture);
            }
        }
        
        internal static string setreminder_therapy_page {
            get {
                return ResourceManager.GetString("setreminder_therapy_page", resourceCulture);
            }
        }
        
        internal static string myReminder {
            get {
                return ResourceManager.GetString("myReminder", resourceCulture);
            }
        }
        
        internal static string timeset {
            get {
                return ResourceManager.GetString("timeset", resourceCulture);
            }
        }
        
        internal static string add_reminder_title {
            get {
                return ResourceManager.GetString("add_reminder_title", resourceCulture);
            }
        }
        
        internal static string inslintype {
            get {
                return ResourceManager.GetString("inslintype", resourceCulture);
            }
        }
        
        internal static string enterinsulin {
            get {
                return ResourceManager.GetString("enterinsulin", resourceCulture);
            }
        }
        
        internal static string mesurements {
            get {
                return ResourceManager.GetString("mesurements", resourceCulture);
            }
        }
        
        internal static string addreminder {
            get {
                return ResourceManager.GetString("addreminder", resourceCulture);
            }
        }
        
        internal static string adddetails {
            get {
                return ResourceManager.GetString("adddetails", resourceCulture);
            }
        }
        
        internal static string contact_us {
            get {
                return ResourceManager.GetString("contact_us", resourceCulture);
            }
        }
        
        internal static string dontforget {
            get {
                return ResourceManager.GetString("dontforget", resourceCulture);
            }
        }
        
        internal static string beyourself {
            get {
                return ResourceManager.GetString("beyourself", resourceCulture);
            }
        }
        
        internal static string dialydiabetics {
            get {
                return ResourceManager.GetString("dialydiabetics", resourceCulture);
            }
        }
        
        internal static string logout {
            get {
                return ResourceManager.GetString("logout", resourceCulture);
            }
        }
        
        internal static string total_number {
            get {
                return ResourceManager.GetString("total_number", resourceCulture);
            }
        }
        
        internal static string misseddays {
            get {
                return ResourceManager.GetString("misseddays", resourceCulture);
            }
        }
        
        internal static string takendays {
            get {
                return ResourceManager.GetString("takendays", resourceCulture);
            }
        }
    }
}
